<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.10deb1 setup script
 * Date: Wed, 30 Jul 2014 15:36:58 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: mysql-1 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'mysql-1';
$cfg['Servers'][$i]['host'] = 'mysql';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['compress'] = true;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'admin';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '53d910e41112d0.56813858';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>